'use client';
import {useEffect,useState} from 'react';
import {DEFAULT_DESCRIPTION_CONFIG,type VehicleDescriptionConfig} from '@autodealers/shared/vehicle-description';
export default function VehicleDescriptionSettings(){
 const [config,setConfig]=useState<VehicleDescriptionConfig>(DEFAULT_DESCRIPTION_CONFIG),[message,setMessage]=useState(''),[busy,setBusy]=useState(true);
 useEffect(()=>{fetch('/api/admin/settings/vehicle-descriptions',{credentials:'include'}).then(async r=>{if(!r.ok)throw Error();setConfig((await r.json()).config);}).catch(()=>setMessage('No se pudo cargar la configuración.')).finally(()=>setBusy(false));},[]);
 const update=(key:keyof VehicleDescriptionConfig,value:unknown)=>setConfig(prev=>({...prev,[key]:value}));
 async function save(){setBusy(true);try{const r=await fetch('/api/admin/settings/vehicle-descriptions',{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});if(!r.ok)throw Error();setConfig((await r.json()).config);setMessage('Configuración de descripciones guardada.');}catch{setMessage('No se pudo guardar la configuración.');}finally{setBusy(false);}}
 const toggles:[keyof VehicleDescriptionConfig,string][]=[['aiVehicleDescriptionsEnabled','Activar descripciones maestras con IA'],['automaticGeneration','Generación inicial automática'],['emojis','Permitir emojis'],['allowManualEdit','Permitir edición manual'],['allowRegeneration','Permitir regeneración']];
 const selects:[keyof VehicleDescriptionConfig,string,string[]][]=[['rollout','Activación gradual',['development','staging','internal','selected','all']],['language','Idioma',['es','en']],['length','Longitud',['short','medium','long']],['tone','Tono',['professional','friendly','direct']],['bulletFormat','Formato de bullets',['bullet','dash','check']]];
 return <section className="space-y-4 rounded-xl border bg-white p-6" aria-label="Configuración de descripciones maestras"><h2 className="text-xl font-bold">Descripción maestra de vehículos</h2><p className="text-sm text-slate-600">Una descripción oficial para inventario, web y redes. Usa el proveedor, las credenciales y los permisos de IA existentes.</p>
 <div className="grid gap-3 md:grid-cols-2">{toggles.map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!config[key]} onChange={e=>update(key,e.target.checked)}/>{label}</label>)}{selects.map(([key,label,values])=><label key={key} className="block text-sm">{label}<select className="mt-1 block w-full rounded border p-2" value={String(config[key])} onChange={e=>update(key,e.target.value)}>{values.map(v=><option key={v} value={v}>{({development:'Desarrollo',staging:'Pruebas',internal:'Usuarios internos',selected:'Dealers seleccionados',all:'Producción completa',es:'Español',en:'Inglés',short:'Corta',medium:'Media',long:'Larga',professional:'Profesional',friendly:'Cercano',direct:'Directo',bullet:'• Punto',dash:'- Guion',check:'✓ Marca'}as Record<string,string>)[v]}</option>)}</select></label>)}</div>
 {(['internalUserIds','tenantIds','forbiddenWords']as const).map(key=><label key={key} className="block text-sm">{{internalUserIds:'IDs de usuarios internos (uno por línea)',tenantIds:'IDs de dealers / tenants seleccionados (uno por línea)',forbiddenWords:'Palabras o frases prohibidas (una por línea)'}[key]}<textarea className="mt-1 block w-full rounded border p-2" rows={3} value={config[key].join('\n')} onChange={e=>update(key,e.target.value.split('\n'))}/></label>)}
 <label className="block text-sm">Máximo de caracteres<input className="ml-3 rounded border p-2" type="number" min={600} max={10000} value={config.maxCharacters} onChange={e=>update('maxCharacters',Number(e.target.value))}/></label>
 <label className="block text-sm">Llamada a la acción (vacía para usar el idioma elegido)<input className="mt-1 block w-full rounded border p-2" value={config.cta} onChange={e=>update('cta',e.target.value)}/></label>
 <label className="block text-sm">Plantilla base<textarea rows={8} className="mt-1 block w-full rounded border p-2 font-mono" value={config.baseTemplate} onChange={e=>update('baseTemplate',e.target.value)}/></label><p className="text-xs text-slate-500">Conserva los bloques {'{title}, {introduction}, {commercial}, {features}, {important}, {cta}'}. La longitud debe ser compatible con las redes donde publiques; el sistema no creará otra versión para acortarla.</p>
 {message&&<p role="status" className="text-sm">{message}</p>}<button type="button" disabled={busy} onClick={()=>void save()} className="rounded-lg bg-primary-600 px-4 py-2 text-white disabled:opacity-50">{busy?'Guardando…':'Guardar configuración de descripciones'}</button></section>;
}
