const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,deps={},globals={}){const exports={};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInNewContext(code,{exports,require:id=>id in deps?deps[id]:require(id),console,process,AbortSignal,setTimeout,clearTimeout,...globals});return exports;}
const equipment=load('packages/shared/src/vehicle-equipment.ts');const marketing=load('packages/shared/src/vehicle-marketing.ts',{'./vehicle-equipment':equipment});const shared=load('packages/shared/src/vehicle-description.ts',{'./vehicle-marketing':marketing,'./vehicle-equipment':equipment});
const copy=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
class Database{
 constructor(){this.rows=new Map();this.queue=Promise.resolve();this.ids=0;}
 collection(path){return this.collectionAt(path);}
 collectionAt(path){const db=this;return {doc(id){return db.ref(path+'/'+(id||'auto'+(++db.ids)))},add:async data=>{const ref=db.ref(path+'/auto'+(++db.ids));await ref.set(data);return ref;},orderBy(field,direction){return{limit(n){return{get:async()=>({docs:[...db.rows].filter(([p])=>p.startsWith(path+'/')&&p.slice(path.length+1).indexOf('/')<0).sort((a,b)=>direction==='desc'?b[1][field]-a[1][field]:a[1][field]-b[1][field]).slice(0,n).map(([p])=>db.snapshot(p))})}}}}};}
 ref(path){const db=this;return{path,id:path.split('/').at(-1),collection:name=>db.collectionAt(path+'/'+name),get:async()=>db.snapshot(path),set:async(data,opts)=>db.rows.set(path,opts?.merge?{...db.rows.get(path),...copy(data)}:copy(data)),update:async data=>{if(!db.rows.has(path))throw Error('not found');db.rows.set(path,{...db.rows.get(path),...copy(data)})}};}
 snapshot(path){return{id:path.split('/').at(-1),exists:this.rows.has(path),data:()=>copy(this.rows.get(path)),ref:this.ref(path)};}
 runTransaction(fn){const run=this.queue.then(async()=>{const writes=[];let writing=false;const tx={get:async ref=>{assert.equal(writing,false,'Firestore transaction cannot read after writes');return this.snapshot(ref.path);},set:(ref,data,opts)=>{writing=true;writes.push(()=>ref.set(data,opts));},update:(ref,data)=>{writing=true;writes.push(()=>ref.update(data));}};const result=await fn(tx);for(const write of writes)await write();return result;});this.queue=run.catch(()=>{});return run;}
}
const vin='1HGCM82633A004352';const vehicle={id:'car',tenantId:'tenant',sellerId:'seller',year:2003,make:'Honda',model:'Accord',price:12000,currency:'USD',mileage:18450,mileageUnit:'mi',condition:'used',vin,specifications:{vin,equipment:equipment.buildVinEquipment({EngineModel:'V6',TransmissionStyle:'Automatic',DriveType:'FWD',Seats:'5',ABS:'Standard',BlindSpotMon:'Optional'},vin)},description:'Texto anterior'};
const actor={userId:'seller',role:'seller',tenantId:'tenant'};
function harness(options={}){
 const db=new Database();const config={...shared.DEFAULT_DESCRIPTION_CONFIG,aiVehicleDescriptionsEnabled:true,rollout:'all',forbiddenWords:[]};db.rows.set('system/vehicle_descriptions',config);db.rows.set('tenants/tenant/vehicles/car',copy(vehicle));let calls=0,body;
 const core={isFeatureEnabled:async()=>true,getAIConfig:async()=>({enabled:true,provider:'openai',contentSettings:{enabled:true}}),getAIApiKey:async()=> 'test-secret-never-log',getAIModel:async()=> 'configured-model',tenantCanGenerateContent:async()=>true};
 const provider=load('packages/inventory/src/vehicle-description-provider.ts',{'@autodealers/core':core,'@autodealers/shared':{getFirestore:()=>db},'@autodealers/shared/vehicle-description':shared},{fetch:async(url,init)=>{calls++;body=JSON.parse(init.body);if(options.delay)await options.delay;if(options.fail)return{ok:false,status:503};return{ok:true,json:async()=>({model:'configured-model',choices:[{finish_reason:'stop',message:{content:JSON.stringify(options.plan||{factIds:['EngineModel','ABS'],introduction:0,commercial:1})}}],usage:{prompt_tokens:120,completion_tokens:60,total_tokens:180}})}}});
 const mod=load('packages/inventory/src/vehicle-description-service.ts',{'@autodealers/core':core,'@autodealers/shared':{getFirestore:()=>db},'@autodealers/shared/vehicle-description':shared,'@autodealers/shared/vehicle-equipment':equipment,'./vehicle-description-persistence':load('packages/inventory/src/vehicle-description-persistence.ts',{'@autodealers/shared/vehicle-description':shared}),'./vehicle-description-provider':provider});
 return{...mod,db,config,provider,get calls(){return calls},get body(){return body},read:()=>copy(db.rows.get('tenants/tenant/vehicles/car'))};
}
test('confirmed VIN facts only; missing, optional and visual guesses excluded',()=>{const input=shared.descriptionInput({...vehicle,suggestedFeatures:[{id:'f',label:'Roof rack',value:'Sí',status:'confirmed'}],privateCost:1});assert.ok(input.facts.some(f=>f.value==='V6'));assert.ok(!input.facts.some(f=>/Optional|Opcional|Roof rack|privateCost/.test(f.value+f.label)));assert.equal(shared.hasDescriptionData({make:'Toyota',model:'Tacoma',year:2025,mileage:12}),true);assert.equal(shared.hasDescriptionData({make:'Toyota'}),false);});
test('OpenAI gets structured allowlisted facts and result cannot invent a fact',async()=>{const h=harness();const generated=await h.VehicleDescriptionService.generateDescription(actor,vehicle,'request_provider_01');assert.match(generated.text,/Honda Accord/);assert.match(generated.text,/V6/);assert.equal(h.body.response_format.json_schema.strict,true);assert.doesNotMatch(JSON.stringify(h.body),/test-secret|sellerId|tenantId|1HGCM82633A004352/);assert.throws(()=>h.provider.renderDescription(vehicle,{factIds:['invented_4WD'],introduction:0,commercial:0},h.config),/unconfirmed/);});
test('vehicle without VIN generates from manual confirmed data',async()=>{const h=harness({plan:{factIds:[],introduction:1,commercial:0}});const result=await h.VehicleDescriptionService.generateDescription(actor,{make:'Toyota',model:'Tacoma',year:2025,mileage:200,mileageUnit:'mi',modifications:['Estribos confirmados']},'request_without_vin');assert.match(result.text,/Tacoma/);assert.match(result.text,/Estribos confirmados/);assert.doesNotMatch(result.text,/4WD|garantía|Carfax|Turbo/);});
test('manual save mirrors master and legacy, preserves history and user',async()=>{const h=harness();await h.VehicleDescriptionService.saveManualDescription(actor,'car','Mi texto manual',0);const record=h.read();assert.equal(record.masterDescription,'Mi texto manual');assert.equal(record.description,record.masterDescription);const history=await h.VehicleDescriptionService.history(actor,'car');assert.equal(history.versions.length,2);assert.ok(history.versions.some(v=>v.text==='Texto anterior'&&v.source==='migration'));assert.ok(history.versions.some(v=>v.text==='Mi texto manual'&&v.userId==='seller'));});
test('regeneration requires confirmation and retains accurate AI metadata on save',async()=>{const h=harness();await assert.rejects(h.VehicleDescriptionService.regenerateDescription(actor,vehicle,'request_regen_confirm','car',false),/confirmation/);const draft=await h.VehicleDescriptionService.regenerateDescription(actor,vehicle,'request_regen_accepted','car',true);await h.VehicleDescriptionService.commit(actor,'car',{masterDescription:draft.text},{draftId:draft.draftId,expectedRevision:0});assert.equal(h.read().descriptionNeedsReview,false);const v=(await h.VehicleDescriptionService.history(actor,'car')).versions.find(v=>v.source==='regeneration');assert.equal(v.model,'configured-model');assert.equal(v.usage.totalTokens,180);});
test('restore appends a version and never destroys later history',async()=>{const h=harness();await h.VehicleDescriptionService.saveManualDescription(actor,'car','Primera',0);await h.VehicleDescriptionService.saveManualDescription(actor,'car','Segunda',1);const versions=(await h.VehicleDescriptionService.history(actor,'car')).versions;await h.VehicleDescriptionService.restoreDescriptionVersion(actor,'car',versions.find(v=>v.text==='Primera').id,2);assert.equal(h.read().masterDescription,'Primera');const restored=(await h.VehicleDescriptionService.history(actor,'car')).versions;assert.equal(restored.length,4);assert.ok(restored.some(v=>v.source==='restore'));});
for(const field of ['mileage','price','modifications'])test(field+' change marks review without replacing manual description',async()=>{const h=harness();await h.VehicleDescriptionService.saveManualDescription(actor,'car','Manual',0);await h.VehicleDescriptionService.commit(actor,'car',{[field]:field==='modifications'?['Aros confirmados']:20000},{expectedRevision:1});assert.equal(h.read().masterDescription,'Manual');assert.equal(h.read().descriptionNeedsReview,true);});
test('provider failure preserves vehicle and writes sanitized audit',async()=>{const h=harness({fail:true});await assert.rejects(h.VehicleDescriptionService.generateDescription(actor,vehicle,'request_api_failure'),/provider_failed/);assert.equal(h.read().description,'Texto anterior');assert.equal(h.read().masterDescription,undefined);assert.ok([...h.db.rows.values()].some(v=>v.status==='error'));assert.doesNotMatch(JSON.stringify([...h.db.rows]),/test-secret-never-log|Authorization/);});
test('roles, tenant boundaries and seller ownership are enforced',async()=>{const h=harness();assert.throws(()=>h.assertDescriptionAccess({...actor,role:'customer'},'tenant'),/forbidden/);assert.throws(()=>h.assertDescriptionAccess(actor,'other'),/forbidden/);await assert.rejects(h.VehicleDescriptionService.saveManualDescription({...actor,userId:'other'},'car','Hacked',0),/forbidden/);});
test('legacy read uses old description; explicitly blank master never revives stale text',()=>{assert.equal(shared.officialVehicleDescription({description:'Legacy'}),'Legacy');assert.equal(shared.officialVehicleDescription({masterDescription:'',description:'Legacy'}),'');assert.equal(marketing.vehicleShareDescription({masterDescription:'Master',description:'Legacy'}),'Master');});
test('concurrent edits: one commit succeeds and the stale edit is rejected',async()=>{const h=harness();const results=await Promise.allSettled([h.VehicleDescriptionService.saveManualDescription(actor,'car','First',0),h.VehicleDescriptionService.saveManualDescription(actor,'car','Second',0)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);assert.equal(h.read().masterDescription,'First');});
test('duplicate generation request calls provider only once',async()=>{let done;const delay=new Promise(r=>done=r);const h=harness({delay});const first=h.VehicleDescriptionService.generateDescription(actor,vehicle,'request_concurrent');await new Promise(r=>setTimeout(r,15));await assert.rejects(h.VehicleDescriptionService.generateDescription(actor,vehicle,'request_concurrent'),/in_progress/);done();await first;await h.VehicleDescriptionService.generateDescription(actor,vehicle,'request_concurrent');assert.equal(h.calls,1);});
test('late AI draft cannot overwrite a newer manual edit',async()=>{const h=harness();const draft=await h.VehicleDescriptionService.regenerateDescription(actor,vehicle,'request_stale_result','car',true);await h.VehicleDescriptionService.saveManualDescription(actor,'car','Keep manual',0);await assert.rejects(h.VehicleDescriptionService.commit(actor,'car',{masterDescription:draft.text},{draftId:draft.draftId,expectedRevision:0}),/conflict/);assert.equal(h.read().masterDescription,'Keep manual');});
test('rollout defaults off and supports environment, user, tenant and full scopes',()=>{const h=harness();assert.equal(h.descriptionRolloutAllowed(shared.DEFAULT_DESCRIPTION_CONFIG,actor),false);for(const [scope,extra,environment]of [['internal',{internalUserIds:['seller']},'production'],['selected',{tenantIds:['tenant']},'production'],['development',{},'development'],['staging',{},'staging'],['all',{},'production']])assert.equal(h.descriptionRolloutAllowed({...h.config,rollout:scope,...extra},actor,environment),true);});
test('visual suggestions cannot reach facts until explicitly confirmed',async()=>{const h=harness();const saved=h.read();saved.photos=['https://example.com/car.jpg'];h.db.rows.set('tenants/tenant/vehicles/car',saved);await h.VehicleDescriptionService.recordPhotoSuggestions(actor,'car',saved.photos[0],[{label:'Roof rack',value:'Visible'}]);assert.ok(!shared.descriptionInput(h.read()).facts.some(f=>f.label==='Roof rack'));const data=await h.VehicleDescriptionService.history(actor,'car');const result=await h.VehicleDescriptionService.confirmSuggestedFeature(actor,'car',data.suggestedFeatures[0].id,0);assert.equal(result.suggestedFeatures[0].confirmedBy,'seller');assert.ok(shared.descriptionInput(h.read()).facts.some(f=>f.label==='Roof rack'));assert.equal(h.read().descriptionNeedsReview,true);});
test('social generator reuses one exact text for Facebook and Instagram without provider calls',async()=>{const mod=load('packages/core/src/social-ai.ts',{'@autodealers/shared/vehicle-marketing':marketing,'./credentials':{},'./ai-config':{},'./membership-ai-gate':{}});const text='Maestra\n'+ 'Descripción completa. '.repeat(40);const result=await mod.generateSocialPost({...vehicle,masterDescription:text});assert.equal(result.text,text);assert.equal(result.optimizedFor.facebook.text,text);assert.equal(result.optimizedFor.instagram.caption,text);});
