export type MembershipType = 'dealer' | 'seller';
export type SubscriptionStatus = 'active' | 'past_due' | 'cancelled' | 'suspended' | 'trialing' | 'unpaid' | 'incomplete' | 'incomplete_expired';
export interface MembershipFeatures {
    maxSellers?: number;
    maxInventory?: number;
    maxCampaigns?: number;
    maxPromotions?: number;
    maxAppointmentsPerMonth?: number;
    maxStorageGB?: number;
    maxApiCallsPerMonth?: number;
    customSubdomain: boolean;
    customDomain: boolean;
    aiEnabled: boolean;
    aiAutoResponses: boolean;
    aiContentGeneration: boolean;
    aiLeadClassification: boolean;
    socialMediaEnabled: boolean;
    socialMediaScheduling: boolean;
    socialMediaAnalytics: boolean;
    marketplaceEnabled: boolean;
    marketplaceFeatured: boolean;
    advancedReports: boolean;
    customReports: boolean;
    exportData: boolean;
    whiteLabel: boolean;
    apiAccess: boolean;
    webhooks: boolean;
    ssoEnabled: boolean;
    multiLanguage: boolean;
    customTemplates: boolean;
    emailMarketing: boolean;
    smsMarketing: boolean;
    whatsappMarketing: boolean;
    videoUploads: boolean;
    virtualTours: boolean;
    liveChat: boolean;
    appointmentScheduling: boolean;
    paymentProcessing: boolean;
    inventorySync: boolean;
    crmAdvanced: boolean;
    leadScoring: boolean;
    automationWorkflows: boolean;
    integrationsUnlimited: boolean;
    prioritySupport: boolean;
    dedicatedManager: boolean;
    trainingSessions: boolean;
    customBranding: boolean;
    mobileApp: boolean;
    offlineMode: boolean;
    dataBackup: boolean;
    complianceTools: boolean;
    analyticsAdvanced: boolean;
    aBTesting: boolean;
    seoTools: boolean;
    customIntegrations: boolean;
    freePromotionsOnLanding: boolean;
    fiModule: boolean;
    fiMultipleManagers: boolean;
    corporateEmailEnabled: boolean;
    maxCorporateEmails?: number;
    emailSignatureBasic: boolean;
    emailSignatureAdvanced: boolean;
    emailAliases: boolean;
    multiDealerEnabled?: boolean;
    maxDealers?: number;
    requiresAdminApproval?: boolean;
}
export interface Membership {
    id: string;
    name: string;
    type: MembershipType;
    price: number;
    currency: string;
    billingCycle: 'monthly' | 'yearly';
    features: MembershipFeatures;
    stripePriceId: string;
    isActive: boolean;
    createdAt: Date;
    updatedAt?: Date;
    lastSyncedAt?: Date;
    syncVersion?: number;
}
export interface Subscription {
    id: string;
    tenantId: string;
    userId: string;
    membershipId: string;
    stripeSubscriptionId: string;
    stripeCustomerId: string;
    status: SubscriptionStatus;
    currentPeriodStart: Date;
    currentPeriodEnd: Date;
    cancelAtPeriodEnd: boolean;
    cancelledAt?: Date;
    lastPaymentDate?: Date;
    nextPaymentDate?: Date;
    daysPastDue?: number;
    suspendedAt?: Date;
    reactivatedAt?: Date;
    paymentAttempts?: number;
    createdAt: Date;
    updatedAt: Date;
}
export interface PaymentMethod {
    id: string;
    type: 'card' | 'bank_account';
    last4: string;
    brand?: string;
    expiryMonth?: number;
    expiryYear?: number;
}
//# sourceMappingURL=types.d.ts.map